=== BattMoTeam/BattMo/Utilities/JsonSchemas/battery.schema.json
{
  "$id": "file://batmo/schemas/battery",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A standard battery",
  "type": "object",
  "properties" : {
    "SOC" : {"type" : "number"},
    "Ucut" : {"type" : "number",
              "description" : "cut voltage"},
    "initT" : {"type" : "number",
               "description" : "Initial temperature"},
    "NegativeElectrode" : {"$ref": "electrode"},
    "PositiveElectrode" : {"$ref": "electrode"},
    "Electrolyte" : {"$ref": "binaryelectrolyte"},
    "ThermalModel" : {"$ref": "thermalmodel"}
  }
}

=== BattMoTeam/BattMo/JsonDatas/Chen2020/chenBattery.json
{
    "initT": 298.15,
    "NegativeElectrode": {
        "electricalConductivity": 215,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "chargeCarrierName": "Li",
        "Interface": {
            "isFile": true,
            "filename": "JsonDatas/Chen2020/chenNegativeElectrodeInterface.json"
        }
    },
    "PositiveElectrode": {
        "electricalConductivity": 0.18,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "chargeCarrierName": "Li",
        "Interface": {
            "isFile": true,
            "filename": "JsonDatas/Chen2020/chenPositiveElectrodeInterface.json"
        }
    },
    "Electrolyte": {
        "filename": "JsonDatas/Chen2020/chenElectrolyte.json",
        "isFile": true
    }
}
